apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  labels:
    app: web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: web-app
          image: REGISTRY_HOSTNAME/light-quest-349811/IMAGE:GITHUB_SHA
          ports:
            - containerPort: 8080
# update replicas to two            
