#image: registry.gitlab.com/charts/alpine-helm
#image: registry.gitlab.com/gitlab-org/cluster-integration/auto-deploy-image:v1.1.0
#image: registry.gitlab.com/gitlab-org/gitlab-build-images:gitlab-charts-build-base-helm-3 #add by me mohamed_th
image: registry.gitlab.com/gitlab-org/cluster-integration/auto-deploy-image:v2.0.0-beta.1
variables:
    AUTO_DEVOPS_FORCE_DEPLOY_V2: 1

stages:
  - test
  - release

lint:
  stage: test
  script:
    #- helm dep update .
    - helm repo add "stable" "https://charts.bitnami.com/bitnami" 
    - helm lint  .
  except:
    - master

release-chart:
  stage: release
  script:
    - curl --fail --request POST --form "token=$CI_JOB_TOKEN" --form ref=master https://gitlab.com/api/v4/projects/2860651/trigger/pipeline
  only:
    - master
