replicaCount: 1

image:
  repository: gitlab.example.com/group/project
  tag: stable
  pullPolicy: Always
  secrets:
    - name: gitlab-registry

podAnnotations: {}

application:
  track: stable
  tier: web
  migrateCommand:
  initializeCommand:
  secretName:
  secretChecksum:

gitlab:
  app:
  env:

service:
  enabled: true
  annotations: {}
  name: web
  type: ClusterIP
  externalPort: 8069
  internalPort: 8069

ingress:
  tls:
    enabled: true
    secretName: ""
  annotations:
    #kubernetes.io/tls-acme: "true"
    #certmanager.k8s.io/acme-challenge-type: http01
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: 2048m
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 2Gi

livenessProbe:
  path: "/monitoring/status"
  scheme: "HTTP"
  initialDelaySeconds: 30
  periodSeconds: 60
  timeoutSeconds: 1800
  failureThreshold: 3
  successThreshold: 1

readinessProbe:
  path: "/monitoring/status"
  scheme: "HTTP"
  initialDelaySeconds: 30
  periodSeconds: 60
  timeoutSeconds: 1800
  failureThreshold: 3
  successThreshold: 1

resources:
#  limits:
#    cpu: 100m
#    memory: 128Mi
#  requests:
#    cpu: 100m
#    memory: 128Mi
#test

postgresql:
  enabled: false
  resources:
    requests:
      memory: 0
      cpu: 0

redis:
  enabled: false
