apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  labels:
    app: web-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: web-app
          image: REGISTRY_HOSTNAME/light-quest-349811/IMAGE:GITHUB_SHA
          ports:
            - containerPort: 8069
          env:
          - name: DB_ENV_POSTGRES_USER
            valueFrom:
               secretKeyRef:
                 name: postgres-secret   
                 key: postgres-username
          - name: DB_ENV_POSTGRES_PASSWORD
            valueFrom:
               secretKeyRef:
                 name: postgres-secret   
                 key: postgres-password   
          - name: DB_PORT_5432_TCP_ADDR
            valueFrom:
               configMapKeyRef:
                 name: postgres-configmap  
                 key: database_url
                
