---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "web-app-service"
  namespace: "default"
  labels:
    app: "web-app"
spec:
  ports:
    - protocol: "TCP"
      port: 80
  selector:
    app: "web-app"
  type: "LoadBalancer"
